# Generated by Django 3.2.8 on 2021-10-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company_rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('base_training_rate', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('activate_rates', models.BooleanField(default=False)),
                ('activate_training_rate', models.BooleanField(default=False)),
                ('ecola_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True)),
                ('activate_ecola', models.BooleanField(default=True)),
                ('activate_overtime', models.BooleanField(default=True)),
                ('activate_1_25_overtime', models.BooleanField(default=True)),
                ('activate_rest_day', models.BooleanField(default=True)),
                ('activate_holiday', models.BooleanField(default=True)),
                ('activate_special', models.BooleanField(default=True)),
                ('activate_night_differential', models.BooleanField(default=True)),
                ('activate_thirteenth_month', models.BooleanField(default=True)),
                ('activate_tardiness', models.BooleanField(default=True)),
                ('activate_sil', models.BooleanField(default=True)),
                ('activate_tshirt', models.BooleanField(default=True)),
                ('activate_rf', models.BooleanField(default=True)),
                ('activate_house', models.BooleanField(default=True)),
                ('activate_misc', models.BooleanField(default=True)),
                ('activate_gatepass', models.BooleanField(default=True)),
                ('activate_medical', models.BooleanField(default=True)),
                ('activate_pants', models.BooleanField(default=True)),
                ('activate_vale', models.BooleanField(default=True)),
                ('activate_uniform', models.BooleanField(default=True)),
                ('activate_company_loan', models.BooleanField(default=True)),
                ('activate_pagibig_loan', models.BooleanField(default=True)),
                ('activate_sss_loan', models.BooleanField(default=True)),
                ('activate_canteen', models.BooleanField(default=True)),
                ('activate_service_fee', models.BooleanField(default=True)),
                ('activate_sunday', models.BooleanField(default=True)),
                ('activate_allowance', models.BooleanField(default=True)),
                ('activate_adjustment', models.BooleanField(default=True)),
                ('activate_transpo_allowance', models.BooleanField(default=True)),
                ('sss', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('philhealth', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('pagibig', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_rates', to='hrms.company')),
            ],
        ),
    ]
