# Generated by Django 3.2.8 on 2021-10-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BracketSSContribEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrib_amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('ranged', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='General_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_company', models.CharField(default='company', max_length=255)),
                ('template_name', models.CharField(default='Company Inc.', max_length=255)),
                ('company_address', models.CharField(default='Company Location', max_length=255)),
                ('company_contacts', models.CharField(default='02 xxx-xxxx / 02 xxx-xxxx', max_length=255)),
            ],
        ),
    ]
